# Generated by Django 4.1.5 on 2023-02-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_noticeboard_question_student_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
