# Generated by Django 4.1.5 on 2023-02-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_noticeboard_created_at_noticeboard_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qn',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(default='options'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
