# Generated by Django 4.1.5 on 2023-03-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_user_avatar_remove_user_bio_remove_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
