# Generated by Django 4.0.5 on 2023-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_user_avatar_remove_user_bio_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('H', 'Hard'), ('M', 'Medium'), ('E', 'Easy')], default='M', max_length=1),
        ),
    ]
